import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/album.module.css'
import * as React from 'react';

export default function Album() {
    return (
        <div className={styles.content}>
            <Head>
                <title>Who Got Us Here</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/oie_png.png" />
            </Head>
            <a className={styles.back} href='/'>⊲Back to Homepage</a>
            <h1 className={styles.title}>Our Family</h1>
            <div className={styles.masonry}>
                <img className={styles.item} src="/album/benlaurakids.jpg"></img>
                <img className={styles.item} src="/album/bikes.jpg"></img>
                <img className={styles.item} src="/album/boat.jpg"></img>
                <img className={styles.item} src="/album/boatkatka.jpg"></img>
                <img className={styles.item} src="/album/cherylchristmas.jpg"></img>
                <img className={styles.item} src="/album/cutetia.jpg"></img>
                <img className={styles.item} src="/album/easter.jpg"></img>
                <img className={styles.item} src="/album/eng1.jpg"></img>
                <img className={styles.item} src="/album/eng2.jpg"></img>
                <img className={styles.item} src="/album/fam1.jpg"></img>
                <img className={styles.item} src="/album/fam2.jpg"></img>
                <img className={styles.item} src="/album/lawnmower.jpg"></img>
                <img className={styles.item} src="/album/littletia2.jpg"></img>
                <img className={styles.item} src="/album/littlewiezoreks.jpg"></img>
                <img className={styles.item} src="/album/Me_and_Tia.jpg"></img>
                <img className={styles.item} src="/album/meske.jpg"></img>
                <img className={styles.item} src="/album/paulsens.jpg"></img>
                <img className={styles.item} src="/album/pigroast.jpeg"></img>
                <img className={styles.item} src="/album/prom.jpg"></img>
                <img className={styles.item} src="/album/snowboard.jpg"></img>
                <img className={styles.item} src="/album/sweeties.jpg"></img>
                <img className={styles.item} src="/album/tia-and-athena.jpg"></img>
                <img className={styles.item} src="/album/tiagrad.jpg"></img>
                <img className={styles.item} src="/album/Tianna.jpg"></img>
                <img className={styles.item} src="/album/waterslide.jpg"></img>
                <img className={styles.item} src="/album/wichmans.jpg"></img>
                <img className={styles.item} src="/album/Wiezorek_Family.jpg"></img>
                <img className={styles.item} src="/album/wiezoreks.jpg"></img>
                <img className={styles.item} src="/album/wiezoreks2.jpg"></img>
                <img className={styles.item} src="/album/wiezoreks3.jpg"></img>
                <img className={styles.item} src="/album/zorro_presents.jpg"></img>
                <img className={styles.item} src="/album/zorro_window.jpg"></img>
                <img className={styles.item} src="/album/Zorro.jpg"></img>
            </div>
            <footer className={styles.footer}><a className={styles.footerURL}>Thank you for being an amazing part of this adventure!</a></footer>
        </div>
    )
}

{/**
"https://nextjs.org"
"https://nextjs.org/docs"
"https://nextjs.org/learn"
"https://github.com/vercel/next.js/tree/canary/examples"
"https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
*/}