import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ben and Tias Wedding!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/oie_png.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Ben and Tia's</a> Wedding Website!
        </h1>

        <p className={styles.description}>
          Thank you for checking out our wedding website! If you are planning on attending, please take the survey where it says RSVP
        </p>
        <img className={styles.engr} src="/eng1.jpg"></img>
        <img className={styles.engl} src="/eng2.jpg"></img>
        <img className={styles.famr} src="/fam1.jpg"></img>
        <img className={styles.faml} src="/fam2.jpg"></img>
        <div className={styles.grid}>
          <a
            href="https://forms.gle/WxpvjU3EmtbboS7A6"
            className={styles.card}
          >
            <h2>RSVP! &raquo;</h2>
            <p>Tell us that you're going to show by filling out a quick survey on your phone.</p>
          </a>
          <a
            href=""
            className={styles.card}
          >
            <h2>Take the Tour &raquo;</h2>
            <p>
              Try out a few of our favorite spots where we shared our first few dates.
            </p>
          </a>
          <a href="" className={styles.card}>
            <h2>Where to Stay &raquo;</h2>
            <p>We've blocked off a rew rooms for you at the ArericInn</p>
          </a>
          <a href="" className={styles.card}>
            <h2>Where to Eat &raquo;</h2>
            <p>Try some of our favorite places around town to eat.</p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.amazon.com/wedding/share/benandtiasweddingregistry"
        >
          Amazon Gift Registry
        </a>
      </footer>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

{/**
"https://nextjs.org"
"https://nextjs.org/docs"
"https://nextjs.org/learn"
"https://github.com/vercel/next.js/tree/canary/examples"
"https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
*/}