import Head from 'next/head'
import styles from '../styles/party.module.css'
import * as React from 'react';

export default function lodging() {
  return (
    <div>
      <Head>
        <title>Meet the Party!</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/oie_png.png" />
      </Head>
      <a className={styles.back} href='/'>⊲Back to Homepage</a>
      <div className={styles.content}>
        <h1 className={styles.title}>Our Wedding Party!</h1>
        <div className={styles.grid}>
          <a
            // href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            // target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/DSC_9254-2.jpg"></img>
            <div>
              <h2>The Bride and Groom &raquo;</h2>
              <p>The lovely couple! Ben and Tia first met in high school and grew close while spending time together on the ski hill. Now out of college, Ben works as a software engineer for TRC. With one more semester, Tia plans on finishing her chemical engineering degree and persuing a career in that field.</p>
            </div>
            <img className={styles.img} src="/DSC_8993-2.jpg"></img>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            // href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            // target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/robandathena.jpg"></img>
            <div>
              <h2>The Best Man and Maid of Honnor &raquo;</h2>
              <p>asdf af asd f asdfg a sd fg asd f as d    asdgasdgasfdg asfhafhgafg a sfdg ashfasf hg asdf h a sdfh a hgsfdghasdfgh asfdhasfh asfhasfhgasdfgha sdfgasdfgasdgfas dgfasdfgasd df asdf a fafsdgfa asdf</p>
            </div>
            <img className={styles.img} src="/placeholder.jpg"></img>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            // href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            // target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/placeholder.jpg"></img>
            <div>
              <h2>Donny Ekholm and Lani Vik &raquo;</h2>
              <p>asdf af asd f asdfg a sd fg asd f as d    asdgasdgasfdg asfhafhgafg a sfdg ashfasf hg asdf h a sdfh a hgsfdghasdfgh asfdhasfh asfhasfhgasdfgha sdfgasdfgasdgfas dgfasdfgasd df asdf a fafsdgfa asdf</p>
            </div>
            <img className={styles.img} src="/placeholder.jpg"></img>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            // href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            // target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/placeholder.jpg"></img>
            <div>
              <h2>Laura Paulsen and MaKayla Temple &raquo;</h2>
              <p>asdf af asd f asdfg a sd fg asd f as d    asdgasdgasfdg asfhafhgafg a sfdg ashfasf hg asdf h a sdfh a hgsfdghasdfgh asfdhasfh asfhasfhgasdfgha sdfgasdfgasdgfas dgfasdfgasd df asdf a fafsdgfa asdf</p>
            </div>
            <img className={styles.img} src="/placeholder.jpg"></img>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            // href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            // target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/tiaparents.jpg"></img>
            <div>
              <h2>The Bride's Parents &raquo;</h2>
              <p>asdf af asd f asdfg a sd fg asd f as d    asdgasdgasfdg asfhafhgafg a sfdg ashfasf hg asdf h a sdfh a hgsfdghasdfgh asfdhasfh asfhasfhgasdfgha sdfgasdfgasdgfas dgfasdfgasd df asdf a fafsdgfa asdf</p>
            </div>
            <img className={styles.img} src="/placeholder.jpg"></img>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            // href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            // target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/placeholder.jpg"></img>
            <div>
              <h2>The Groom's Parents &raquo;</h2>
              <p>asdf af asd f asdfg a sd fg asd f as d    asdgasdgasfdg asfhafhgafg a sfdg ashfasf hg asdf h a sdfh a hgsfdghasdfgh asfdhasfh asfhasfhgasdfgha sdfgasdfgasdgfas dgfasdfgasd df asdf a fafsdgfa asdf</p>
            </div>
            <img className={styles.img} src="/placeholder.jpg"></img>
          </a>
        </div>
      </div>
    </div>
  );
}

// Black Cat        https://blackcatashland.com/
// Ashland Cinema   http://www.ashlandbaycinema.com/
// Houghton Point   https://www.google.com/maps/place/Houghton+Point/@46.6985625,-90.8617169,15z/data=!3m1!4b1!4m5!3m4!1s0x52a91a4f033e8c03:0x1b589ab84558e2a8!8m2!3d46.6985487!4d-90.8529621
// Ashwabay         https://www.google.com/maps/place/Mt+Ashwabay+Ski+and+Recreation+Area/@46.7763496,-90.8931916,13.58z/data=!4m5!3m4!1s0x52a91e86044109f9:0xb011f73ec5926153!8m2!3d46.7772179!4d-90.8945541
//

//https://www.wyndhamhotels.com/americinn/ashland-wisconsin/americinn-ashland/overview?CID=LC:AA::GGL:RIO:National:52038&iata=00093796