import Head from 'next/head'
import styles from '../styles/lodging.module.css'
import * as React from 'react';

export default function lodging() {
  return (
    <div>
      <Head>
        <title>Registry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/oie_png.png" />
      </Head>
      <a className={styles.back} href='/'>⊲Back to Homepage</a>
      <div className={styles.content}>
        <h1 className={styles.title}>Give us Stuff</h1>
        {/* <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/AmericInn+by+Wyndham+Ashland/@46.6100792,-90.8483867,15.25z/data=!4m8!3m7!1s0x52a9110cda18fda9:0xf0c066fc1e3619ff!5m2!4m1!1i2!8m2!3d46.6100477!4d-90.8443359?hl=en&authuser=0"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/lodging/americinn.jpg"></img>
            <div>
              <h2>AmericInn &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/Quality+Inn+Ashland+-+Lake+Superior/@46.5870746,-90.9375604,16z/data=!4m8!3m7!1s0x52a915de2cc84285:0x9a843c751ae50372!5m2!4m1!1i2!8m2!3d46.5870911!4d-90.9368495?hl=en&authuser=0"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <div>
              <h2>Quality Inn &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
            <img className={styles.img} src="/lodging/qualityinn.jpg"></img>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/Best+Western+The+Hotel+Chequamegon/@46.5938222,-90.8889285,15.25z/data=!4m8!3m7!1s0x0:0xea88f2511f684003!5m2!4m1!1i2!8m2!3d46.5928219!4d-90.8850217?hl=en&authuser=0"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/lodging/hotelchequamegon.webp"></img>
            <div>
              <h2>Hotel Chequamegon &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
          </a>
        </div> */}
      </div>
    </div>
  );
}

// Black Cat        https://blackcatashland.com/
// Ashland Cinema   http://www.ashlandbaycinema.com/
// Houghton Point   https://www.google.com/maps/place/Houghton+Point/@46.6985625,-90.8617169,15z/data=!3m1!4b1!4m5!3m4!1s0x52a91a4f033e8c03:0x1b589ab84558e2a8!8m2!3d46.6985487!4d-90.8529621
// Ashwabay         https://www.google.com/maps/place/Mt+Ashwabay+Ski+and+Recreation+Area/@46.7763496,-90.8931916,13.58z/data=!4m5!3m4!1s0x52a91e86044109f9:0xb011f73ec5926153!8m2!3d46.7772179!4d-90.8945541
//

//https://www.wyndhamhotels.com/americinn/ashland-wisconsin/americinn-ashland/overview?CID=LC:AA::GGL:RIO:National:52038&iata=00093796