import Head from 'next/head'
import styles from '../styles/tour.module.css'
import * as React from 'react';

export default function Tour() {
  return (
    <div>
      <Head>
        <title>Our Story</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/oie_png.png" />
      </Head>
      <a className={styles.back} href='/'>⊲Back to Homepage</a>
      <div className={styles.content}>
        <h1 className={styles.title}>The Tour</h1>
        {/* Black Cat */}
        <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/Black+Cat+Coffeehouse/@46.5882209,-90.8924748,16.21z/data=!4m5!3m4!1s0x52a9141db695bb0d:0x3d1dc50480469dc4!8m2!3d46.5877945!4d-90.8904107"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/tour/black-cat-coffeehouse.jpg"></img>
            <div>
              <h2>Black Cat Coffee &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
          </a>
        </div>
        {/* Cinema */}
        <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/Bay+Theater/@46.591085,-90.8919853,16.29z/data=!4m5!3m4!1s0x52a9141d451cf759:0x434401068429c7f5!8m2!3d46.5893083!4d-90.887912"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <div>
              <h2>Ashland Bay Cinema &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
            <img className={styles.img} src="/tour/bay-theater.jpg"></img>
          </a>
        </div>
        {/* Ashwabay */}
        <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/Mt+Ashwabay+Ski+and+Recreation+Area/@46.7763496,-90.8931916,13.58z/data=!4m5!3m4!1s0x52a91e86044109f9:0xb011f73ec5926153!8m2!3d46.7772179!4d-90.8945541"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <img className={styles.img} src="/tour/ashwabay.jpg"></img>
            <div>
              <h2>Ashwabay Ski Hill &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
          </a>
        </div>
        {/* Houghton Point */}
        <div className={styles.grid}>
          <a
            href="https://www.google.com/maps/place/Houghton+Point/@46.6985625,-90.8617169,15z/data=!3m1!4b1!4m5!3m4!1s0x52a91a4f033e8c03:0x1b589ab84558e2a8!8m2!3d46.6985487!4d-90.8529621"
            target='_blank' rel='noopener noreferrer'
            className={styles.card}
          >
            <div>
              <h2>Houghton Point Hike &raquo;</h2>
              <p>fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd fasdfa sdfasd </p>
            </div>
            <img className={styles.img} src="/tour/black-cat-coffeehouse.jpg"></img>
          </a>
        </div>
      </div>
    </div>
  );
}

// Black Cat        https://blackcatashland.com/
// Ashland Cinema   http://www.ashlandbaycinema.com/
// Houghton Point   https://www.google.com/maps/place/Houghton+Point/@46.6985625,-90.8617169,15z/data=!3m1!4b1!4m5!3m4!1s0x52a91a4f033e8c03:0x1b589ab84558e2a8!8m2!3d46.6985487!4d-90.8529621
// Ashwabay         https://www.google.com/maps/place/Mt+Ashwabay+Ski+and+Recreation+Area/@46.7763496,-90.8931916,13.58z/data=!4m5!3m4!1s0x52a91e86044109f9:0xb011f73ec5926153!8m2!3d46.7772179!4d-90.8945541
// 